Repository pivotal-cf/docs-pcf-install, pull requests merged in 2018-03, with the labels that each got.

#329 Fixing the variable to use for performing backups from BOSH-CLIENT-SE…
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: scheduled

#321 Changing Redis version
  upgrading-pcf.html.md.erb
Labels: scheduled

#330 Add a missing step to Restore PCF 1.12
  backup-restore/restore-pcf-bbr.html.md.erb
Labels: scheduled

#328 Describe using the Ops Manager API for installation_settings import/export
  backup-restore/backup-pcf-bbr.html.md.erb
  backup-restore/restore-pcf-bbr.html.md.erb
Labels: scheduled

#335 Fix punctuation
  small-footprint.html.md.erb
Labels: unscheduled

#323 External database is default with gcp terraform install.
  gcp-prepare-env-terraform.html.md.erb
Labels: scheduled

#338 Correcting addons section in upgrading docs
  upgrading-pcf.html.md.erb
Labels: scheduled

#339 Create blobstore gcp service account key for gcp.
  gcp-prepare-env-terraform.html.md.erb
Labels: scheduled

#340 Document Backup and Restore of Versioned S3 blobstore
  _filestore_s3_config.html.md.erb
  backup-restore/backup-pcf-bbr.html.md.erb
  backup-restore/disaster-recovery.html.md.erb
  backup-restore/restore-pcf-bbr.html.md.erb
Labels: in progress

#344 Remove incorrect information about uaa backup in backing up PCF doc
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: scheduled

#345 Remove incorrect information about uaa backup in backing up PCF doc
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: scheduled

#347 Fix incorrect information.
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: unscheduled

#341 Docs for Azure install using Terraform
  azure-deploy-terraform.html.md.erb
  azure-om-config-terraform.html.md.erb
Labels: in progress

#348 Clarify that 1.12 always required 1.10.x or later
  upgrading-pcf.html.md.erb
Labels: unscheduled

#349 add IP ranges limitation
  backup-restore/restore-pcf-bbr.html.md.erb
Labels: unscheduled

#350 add IP range limitation
  backup-restore/restore-pcf-bbr.html.md.erb
Labels: in progress

#351 Add IP range limitation
  backup-restore/restore-pcf-bbr.html.md.erb
Labels: unscheduled

#352 add IP range limitation
  backup-restore/restore-pcf-bbr.html.md.erb
Labels: unscheduled

#354 Update BBR supported components section
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: in progress

#355 Update BBR supported components section
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: in progress

#356 Update BBR supported components section
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: in progress

#357 Update BBR supported components section
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: in progress

#319 1.11 manually configure aws step 4 change route table for public subnets
  images/pcfaws/pcf_aws_route_table_az0.png
  images/pcfaws/pcf_aws_route_table_edit_az1.png
  pcf-aws-manual-config.html.md.erb
Labels: scheduled

#358 Clarifying how to retrieve self-signed NSX CA Cert
  vsphere-config.html.md.erb
Labels: scheduled

#359 Corrected typo Directory > Director
  backup-restore/restore-pcf-bbr.html.md.erb
Labels: unscheduled
