Repository pivotal-cf/docs-pcf-install, pull requests merged in 2018-07, with the labels that each got.

#422 Add a step to verify the backup prepare node is deployed
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: scheduled

#423 Add a step to verify the backup prepare node is deployed
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: scheduled

#424 Add a step to verify the backup prepare node is deployed
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: scheduled

#433 Mention in Supported components that BBR supports TLS
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: scheduled

#436 Fix broken anchors pointing to open source docs
  _filestore_s3_config.html.md.erb
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: unscheduled

#437 2.1 fix enable versioning link
  _filestore_s3_config.html.md.erb
  aws-er-config-terraform.html.md.erb
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: unscheduled

#438 Remove Prep 12 from upgrade instructions
  upgrading-pcf.html.md.erb
Labels: unscheduled

#439 Include: S3 bucket unique naming reqs
  pcf-aws-manual-config.html.md.erb
  policy-doc.html.md.erb
Labels: unscheduled

#435 Fix typo: from app_domain to apps_domain
  azure-er-config-terraform.html.md.erb
Labels: unscheduled

#441 Update pcf-aws-manual-config.html.md.erb
  pcf-aws-manual-config.html.md.erb
Labels: unscheduled

#447 note credhub fix in 2.0.17
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: scheduled

#456 Update aws-er-config-terraform.html.md.erb
  aws-er-config-terraform.html.md.erb
Labels: scheduled

#449 move `--os-disk-size-gb` to correct invocation
  azure-om-deploy.html.md.erb
Labels: unscheduled

#451 Documentation to enable external blobstore backup using SDK addon on PCF 1.12
  _filestore_azure_config.html.md.erb
  _filestore_s3_config.html.md.erb
  backup-restore/enabling-external-blobstore-backups.html.md.erb
Labels: scheduled

#450 Documentation to enable external blobstore backup on PCF 1.11
  _filestore_azure_config.html.md.erb
  _filestore_s3_config.html.md.erb
  backup-restore/enabling-external-blobstore-backups.html.md.erb
Labels: scheduled

#452 Documentation to enable external blobstore backup using SDK addon on PCF 2.0
  _filestore_azure_config.html.md.erb
  _filestore_s3_config.html.md.erb
  backup-restore/enabling-external-blobstore-backups.html.md.erb
Labels: scheduled

#453 Documentation to enable external blobstore backup using SDK addon on PCF 2.1
  _filestore_azure_config.html.md.erb
  _filestore_s3_config.html.md.erb
  backup-restore/enabling-external-blobstore-backups.html.md.erb
  upgrading-pcf.html.md.erb
Labels: scheduled

#454 Documentation to enable external blobstore backup using SDK addon on PCF 2.2
  _filestore_azure_config.html.md.erb
  backup-restore/backup-pcf-bbr.html.md.erb
  backup-restore/enabling-external-blobstore-backups.html.md.erb
  upgrading-pcf.html.md.erb
Labels: scheduled

#458 Remove unused page for in place restore
  backup-restore/in-place-restore.html.md.erb
Labels: in progress

#459 Remove unused page for in place restore
  backup-restore/in-place-restore.html.md.erb
Labels: in progress

#460 Remove unused page for in place restore
  backup-restore/in-place-restore.html.md.erb
Labels: in progress

#465 Reintroduce validation of backup using in-place restore
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: unscheduled

#464 Reintroduce validation of backup using in-place restore
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: unscheduled

#463 Reintroduce validation of backup using in-place restore
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: unscheduled

#462 Reintroduce validation of backup using in-place restore
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: unscheduled

#466 Fix 2.2 branch upgrade docs
  upgrading-products.html.md.erb
Labels: unscheduled

#467 Fix 2.1 branch for upgrade docs
  upgrading-products.html.md.erb
Labels: unscheduled

#468 Fix 2.0 branch upgrade docs
  upgrading-products.html.md.erb
Labels: unscheduled

#474 Remove repeated partial 'xforwarded_client_cert_xfcc'
  gcp-er-config.html.md.erb
Labels: unscheduled

#473 Fixed grammer
  gcp-er-config.html.md.erb
Labels: unscheduled
