Repository pivotal-cf/docs-pcf-install, pull requests merged in 2018-10, with the labels that each got.

#529 Wrong topic name
  gcp-om-deploy.html.md.erb
Labels: unscheduled

#530 Instruct operators to run `bbr backup-cleanup` after cancelling backup
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: in progress

#524 Swicth OM instance type from m3 to m5 for AWS
  aws-om-upgrade.html.md.erb
  images/pcfaws/aws_ami_m3large.png
  images/pcfaws/aws_ami_m5large.png
  pcf-aws-manual-config.html.md.erb
Labels: in progress

#532 Add optional step to restore pre-provisioned service data
  backup-restore/restore-pcf-bbr.html.md.erb
Labels: unscheduled

#531 address range fix
  azure-om-deploy.html.md.erb
Labels: unscheduled

#533 URL link for a KB article is obsolted
  _using_ldap_server_ops_manager.html.md.erb
Labels: unscheduled

#539 Revert "There is no need to upload stemcells in Step 4 of restoring PCF"
  backup-restore/restore-pcf-bbr.html.md.erb
Labels: unscheduled

#538 Revert "There is no need to upload stemcells in Step 4 of restoring PCF"
  backup-restore/restore-pcf-bbr.html.md.erb
Labels: unscheduled

#537 Revert "There is no need to upload stemcells in Step 4 of restoring PCF"
  backup-restore/restore-pcf-bbr.html.md.erb
Labels: unscheduled

#536 Revert "remove upload stemcell step[#159729069]"
  backup-restore/restore-pcf-bbr.html.md.erb
Labels: unscheduled

#535 Revert "remove upload stemcell step"
  backup-restore/restore-pcf-bbr.html.md.erb
Labels: unscheduled

#534 Remove AzureStack VM Size adjustment
  azure-om-config.html.md.erb
Labels: unscheduled

#542 Update azure-arm-template.html
  azure-arm-template.html.md.erb
Labels: unscheduled

#541 Update azure-arm-template.html
  azure-arm-template.html.md.erb
Labels: unscheduled

#545 Update Security Groups for OpenStack
  openstack-setup.html.md.erb
Labels: unscheduled

#546 Update link to OpsManager API docs to 2.3
  ops-man-api.html.md.erb
Labels: scheduled

#547 Fix args for replicator
  installing-pcf-is.html.md.erb
Labels: unscheduled

#549 Remove "Ops manager is deployed by BOSH"
  deploy-bosh-om.html.md.erb
Labels: unscheduled

#550 Remove "Ops manager is deployed by BOSH"
  deploy-bosh-om.html.md.erb
Labels: unscheduled
