Repository pivotal-cf/docs-pcf-install, pull requests merged in 2018-08, with the labels that each got.

#480 Removing Azure ARM references.
  azure-arm-template.html.md.erb
  azure-er-config.html.md.erb
  azure-om-config.html.md.erb
  azure-om-deploy.html.md.erb
  azure-om-upgrade.html.md.erb
  azure-prepare-env.html.md.erb
  azure-troubleshooting.html.md.erb
  azure.html.md.erb
  backup-restore/backup-pcf-bbr.html.md.erb
  backup-restore/restore-pcf-bbr.html.md.erb
  deploy-bosh-om.html.md.erb
  index.html.md.erb
  pcf-azure-manual-config.html.md.erb
Labels: scheduled

#484 Correct supported components to document all supported external blobstores
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: unscheduled

#483 Correct supported components to document all supported external blobstores
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: unscheduled

#482 Master bbr minor fixes
  backup-restore/backup-pcf-bbr.html.md.erb
  backup-restore/restore-pcf-bbr.html.md.erb
Labels: unscheduled

#485 There is no need to upload stemcells in Step 4 of restoring PCF 2.2, 2.1
  backup-restore/restore-pcf-bbr.html.md.erb
Labels: unscheduled

#488 Fix import settings cmd
  backup-restore/restore-pcf-bbr.html.md.erb
Labels: unscheduled

#486 There is no need to upload stemcells in Step 4 of restoring PCF 2.0, 1.12, 1.11
  backup-restore/restore-pcf-bbr.html.md.erb
Labels: in progress

#490 Update AWS Permissions Required by Terraform
  aws-prepare-env-terraform.html.md.erb
Labels: scheduled

#492 Remove documentation on bbr exit codes from all branches
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: unscheduled

#493 Update warning that BBR requires add-on for external blobstores
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: unscheduled

#494 Update BOSH UAA client authentication
  opsman-create-bosh-client.html.md.erb
  opsmanager-create-bosh-client.html.md.erb
Labels: unscheduled

#495 Update BOSH UAA client authentication
  opsman-create-bosh-client.html.md.erb
  opsmanager-create-bosh-client.html.md.erb
Labels: scheduled

#496 Rename BBR Prepare Node to Restore Node
  backup-restore/backup-pcf-bbr.html.md.erb
  backup-restore/enabling-external-blobstore-backups.html.md.erb
  backup-restore/images/backup-restore-node.png
Labels: unscheduled

#491 Update the manual steps to deploy OpsMan on Azure
  azure-om-deploy.html.md.erb
Labels: unscheduled

#499 Update gcp-prepare-env-terraform.html.md.erb
  gcp-prepare-env-terraform.html.md.erb
Labels: scheduled

#501 Backup prepare node cleanup
  mysql_bootstrap_ert.html.md.erb
  upgrading-pcf.html.md.erb
Labels: unscheduled

#500 Fixed typo at Step 23 at "Deploying PAS on AWS"
  pcf-aws-manual-er-config.html.md.erb
Labels: unscheduled
