Repository pivotal-cf/docs-pcf-install, pull requests merged in 2018-05, with the labels that each got.

#380 Fix off by one count
  gcp-prepare-env.html.md.erb
Labels: scheduled

#364 Fixes and small improvements to BBR docs for PCF 2.1
  backup-restore/_bosh_target_director_bbr.html.md.erb
  backup-restore/backup-pcf-bbr.html.md.erb
  backup-restore/restore-pcf-bbr.html.md.erb
  backup-restore/system-setup-bbr.html.md.erb
  images/ccdb-encrypt-creds.png
Labels: scheduled

#385 Add new page to document how to enable external blobstore backups
  backup-restore/enabling-external-blobstore-backups.html.md.erb
Labels: scheduled

#386 Add new page to document how to enable external blobstore backups
  backup-restore/enabling-external-blobstore-backups.html.md.erb
Labels: scheduled

#375 Add disaster recovery documentation for PCF 1.11 and 1.12
  backup-restore/disaster-recovery.html.md.erb
Labels: in progress

#376 Add disaster recovery documentation to PCF 1.11 and 1.12
  backup-restore/disaster-recovery.html.md.erb
Labels: scheduled

#379 Update _stopping_cc_boshv2.html.md.erb
  backup-restore/_stopping_cc_boshv2.html.md.erb
Labels: scheduled

#390 Fixes and improvements to BBR docs for PCF 2.2
  backup-restore/_bosh_target_director_bbr.html.md.erb
  backup-restore/backup-pcf-bbr.html.md.erb
  backup-restore/restore-pcf-bbr.html.md.erb
  backup-restore/system-setup-bbr.html.md.erb
  images/ccdb-encrypt-creds.png
Labels: scheduled

#391 Update NSX Certificate Fetching Guidance
  vsphere-config.html.md.erb
Labels: scheduled

#392 Fixes and improvements to BBR docs for PCF 2.0
  backup-restore/_bosh_target_director_bbr.html.md.erb
  backup-restore/backup-pcf-bbr.html.md.erb
  backup-restore/restore-pcf-bbr.html.md.erb
  backup-restore/system-setup-bbr.html.md.erb
  images/ccdb-encrypt-creds.png
Labels: scheduled

#387 Subnet CIDRs specified in the doc do not match the subnet CIDRs in Terraform
  azure-om-config-terraform.html.md.erb
Labels: scheduled

#384 Add S3 backup add-on note about upgrading to 2.1
  upgrading-pcf.html.md.erb
Labels: scheduled

#383 Add new page Enabling external blobstore backups
  backup-restore/enabling-external-blobstore-backups.html.md.erb
  upgrading-pcf.html.md.erb
Labels: scheduled

#395 Corrected Terraform output attribute names
  aws-om-config-terraform.html.md.erb
Labels: scheduled

#404 Update pcf_azure.html.md.erb
  pcf_azure.html.md.erb
Labels: scheduled

#398 Updated PAS tile image
  aws-er-config-terraform.html.md.erb
  images/pas-tile.png
Labels: scheduled

#410 Add note about GDPR to BBR docs
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: unscheduled
