Repository pivotal-cf/docs-pcf-install, pull requests merged in 2018-06, with the labels that each got.

#411 haproxy tls forward ca cert note to include referenced CA api endpoint
  _haproxy_router_tls_forward.html.md.erb
Labels: scheduled

#425 Fix minor typo in example `gcloud ssh` command
  trouble-advanced.html.md.erb
Labels: unscheduled

#417 Move GDPR message to Backup and Restore main page
  backup-restore/backup-pcf-bbr.html.md.erb
  backup-restore/index.html.md.erb
Labels: in progress

#420 Move GDPR message to Backup and Restore main page
  backup-restore/backup-pcf-bbr.html.md.erb
  backup-restore/index.html.md.erb
Labels: in progress

#419 Move GDPR message to Backup and Restore main page
  backup-restore/backup-pcf-bbr.html.md.erb
  backup-restore/index.html.md.erb
Labels: unscheduled

#418 Move GDPR message to Backup and Restore main page
  backup-restore/backup-pcf-bbr.html.md.erb
  backup-restore/index.html.md.erb
Labels: in progress

#421 Addition of Standard sku Load Balancers
  azure-om-deploy.html.md.erb
Labels: unscheduled

#426 Document reduced bbr downtime
  backup-restore/disaster-recovery.html.md.erb
Labels: unscheduled

#431 fix aws permissions guidelines link in install guide
  pcf-aws-manual-config.html.md.erb
Labels: unscheduled

#415 Added switch for disk size for managed disk
  azure-om-deploy.html.md.erb
Labels: unscheduled

#429 Corrects ALB name created by ARM template and provides azure cli comm…
  azure-er-config.html.md.erb
Labels: unscheduled

#342 WIP Copy-edit 1.12 restore PCF docs
  backup-restore/restore-pcf-bbr.html.md.erb
Labels: unscheduled

#427 Document reduced bbr downtime
  backup-restore/disaster-recovery.html.md.erb
Labels: in progress

#414 Documentation Fixes for PCF GCP Terraform Deployment
  _download-stemcell.html.md.erb
  gcp-er-config-terraform.html.md.erb
  gcp-prepare-env-terraform.html.md.erb
Labels: unscheduled

#430 Replace old ert reference for pas
  gcp-prepare-env.html.md.erb
Labels: unscheduled
