Repository pivotal-cf/docs-pcf-install, pull requests merged in 2018-04, with the labels that each got.

#360 GCP External Database is Optional.
  gcp-prepare-env-terraform.html.md.erb
Labels: scheduled

#363 Detail Diego SSH LB for Azure.
  azure-er-config-terraform.html.md.erb
  azure-er-config.html.md.erb
  azure-om-deploy.html.md.erb
  gcp-er-config-terraform.html.md.erb
Labels: scheduled

#362 gorouter health check to specify http 1.0 protocol
  f5-lb.html.md.erb
Labels: scheduled

#374 Replace how does bbr work section with a link
  backup-restore/disaster-recovery.html.md.erb
Labels: unscheduled

#373 Replace how does bbr work section with a link
  backup-restore/disaster-recovery.html.md.erb
Labels: unscheduled

#372 Replace how does bbr work section with a link
  backup-restore/disaster-recovery.html.md.erb
Labels: unscheduled

#366 AWS OM Private Key is marked as sensitive.
  aws-om-config-terraform.html.md.erb
Labels: in progress

#378 Change ERT to PAS
  gcp-er-config.html.md.erb
Labels: scheduled

#371 Update gcp-prepare-env-terraform.html.md.erb
  gcp-prepare-env-terraform.html.md.erb
Labels: scheduled
