Repository pivotal-cf/docs-pcf-install, pull requests merged in 2020-01, with the labels that each got.

#633 [2.7]Remove incorrect reference to backup of uaa DB in director backup
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: scheduled

#632 [2.6] Remove incorrect reference to backup of uaa DB in director backup
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: unscheduled

#631 [2.5] Remove incorrect reference to backup of uaa DB in director backup
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: unscheduled

#634 clarify bosh log-in Director credentials source
  trouble-advanced.html.md.erb
Labels: in progress

#630 [2.4] Remove incorrect reference to backup of uaa DB in director backup
  backup-restore/backup-pcf-bbr.html.md.erb
Labels: scheduled

#636 Documents the Ops Manager syslog format
  pcf-interface.html.md.erb
Labels: scheduled

#635 Documents the Ops Manager syslog format
  pcf-interface.html.md.erb
Labels: in progress

#622 Update docs to reflect that Alana can now update blobstore location
  lock-on-deploy.html.md.erb
Labels: scheduled

#623 Update docs around External MySQL Database fields + advanced mode
  lock-on-deploy.html.md.erb
Labels: scheduled

#629 Parition and Encryption key name are locked after deploy
  lock-on-deploy.html.md.erb
Labels: scheduled

#621 Update docs for locked fields under S3 Blobstore
  lock-on-deploy.html.md.erb
Labels: scheduled
